export const LANGUAGES = ["en", "es", "es-AR"] as const;
export type Language = (typeof LANGUAGES)[number];

const english = {
  logout:"Log out", loggingOut:"Logging out...", resume:"Resume", settings:"Settings", general:"General", personalization:"Personalization", nickname:"Username", language:"Language",
  glyphSet:"Glyph set", avatar:"Avatar", theme:"Theme", chest:"Chest", default:"Default", numeric:"Numeric",
  dark:"Dark", light:"Light", pink:"Pink", ocean:"Ocean", previous:"Previous", next:"Next", closeSettings:"Close settings",
  saveChanges:"Save changes", saving:"Saving...", settingsSaved:"Preferences saved.", settingsError:"Could not save settings.",
  welcome:"Welcome", online:"Online", inDevelopment:"In development", store:"Store", ranking:"Ranking", tutorial:"How to play?",
  play:"Play", back:"Back", loading:"Loading...", retry:"Try again", login:"Log in", signup:"Sign up",
  loginTitle:"Log in", loginSubtitle:"Log in to play.", email:"Email", password:"Password", showPassword:"Show password",
  hidePassword:"Hide password", loggingIn:"Logging in...", loginError:"Could not log in", connectionError:"Connection error. Try again.",
  noAccount:"Don't have an account?", createAccount:"Create account", signupSubtitle:"Sign up to play Gemlocks.",
  username:"Username", usernameRequired:"Username is required.", usernameMin:"Must be at least 4 characters.",
  usernameMax:"Must be at most 16 characters.", usernameStart:"Must start with a letter.", usernameChars:"Only lowercase letters and numbers are allowed.",
  passwordRequired:"Password is required.", passwordMin:"Must be at least 8 characters.", passwordMax:"Must be at most 64 characters.",
  passwordSpaces:"Must not contain spaces.", passwordLetter:"Must contain at least one letter.", passwordNumber:"Must contain at least one number.",
  emailRequired:"Email is required.", signupError:"Could not create account.", creating:"Creating...",
  usernameHint:"4–16 characters · starts with a letter · lowercase letters and numbers only",
  passwordHint:"8–64 characters · at least one letter and one number · no spaces",
  rankPoints:"3 points per win · 1 per draw", position:"Rank", player:"Player", victories:"Wins", defeats:"Losses",
  draws:"Draws", points:"Pts.", noPlayers:"There are no players yet.", rankingError:"Could not load the ranking.",
  backPage:"Previous", nextPage:"Next", page:"Page",
  purchaseError:"Could not complete the purchase.", acquired:"Purchased", confirmChest:"Would you like to get this chest?", confirmPurchase:"Are you sure you want to buy", purchaseRemaining:"After purchase, you'll have", purchasing:"Purchasing...", purchase:"Buy", level:"Level", abandon:"Leave match", toss:"toss",
  storeBalance:"Your balance", coins:"Coins", gems:"Gems", buyCoins:"Get coins", glyphsCategory:"Glyphs", glyphsDescription:"New, varied symbols for building your code", powerUps:"Power-ups", powerUpsDescription:"Powers to gain an advantage in amateur matches", gemlocksCategory:"Gemlocks", gemlocksDescription:"Get chests to customize your treasure", themesCategory:"Themes", themesDescription:"Change the look of the whole game", avatarsCategory:"Avatars", avatarsDescription:"An icon to represent your account", modesCategory:"Modes", modesDescription:"Create online matches with different game modes", bundlesCategory:"Bundles", bundlesDescription:"Themed collections with several items", return:"Back", specialBundles:"Special bundles", specialBundlesDescription:"Themed collections that group several items in one purchase.", coinPacksTitle:"Coin packs", coinPacksSubtitle:"Choose the boost that best fits your game.", popular:"Popular", smallHelp:"A little help", initialBoost:"An initial boost", betterValue:"More coins, better value", advanceMore:"For much faster progress", comingSoon:"Coming soon", futureNote:"Contents are initial proposals; prices and availability will be defined later.", coinsUnavailable:"Coin packs are not available for purchase yet. Prices are indicative and may change.", sectionUnavailable:"This section is not available yet.",
  gameMode:"player vs machine", codePrompt:"The opponent will try to discover these 4 glyphs.", difficultyPrompt:"A race to discover your opponent's secret code.", whoStarts:"Who starts?", coinFinished:"coin toss complete", yourCode:"Your code:", yourAttacks:"your attacks", history:"History", historyEmpty:"No attacks yet.", discardHint:"Choose which glyphs you want to discard:", startingUnlock:"Unlocking...", unlock:"Unlock", start:"Start", confirmClose:"Are you sure you want to leave the match?", leaveCountsAsLoss:"This will count as a loss.", cancel:"Cancel", closeMatch:"Leave match",
  tutorialCodeTitle:"Build a code", tutorialCodeText:"Each player has a secret code made of 4 unique glyphs. Discover your opponent's code before they discover yours.", tutorialDifficultyTitle:"Choose difficulty", tutorialDifficultyText:"Choose one of five levels before starting. Difficulty determines how the machine thinks and chooses its attacks.", tutorialCoinTitle:"The first turn is decided", tutorialCoinText:"A coin toss decides who starts the match.", tutorialAttackTitle:"Attack", tutorialAttackText:"Build a code on your turn and attack. Each attack is compared with your opponent's secret code.", tutorialResultsTitle:"Attack results", tutorialResultsText:"Perfects indicate correct glyphs in the correct position. Regulars indicate correct glyphs in another position.", tutorialDiscardTitle:"Use discard", tutorialDiscardText:"If you think a glyph is not part of the code, enable Discard to mark it and keep track visually during the match.", tutorialWinTitle:"Win the match", tutorialWinText:"The first player to discover the opponent's code wins. Four perfects mean the attacker found the code.", tutorialLabel:"Tutorial", tutorialClose:"Close", tutorialBack:"Back", tutorialNext:"Next", tutorialSecret:"Secret", tutorialAttackLabel:"Attack", tutorialDifficulty:"Difficulty",
  codeTitle:"Choose your code", difficultyTitle:"Choose difficulty", coinToss:"Tossing the coin", startMatchTitle:"Match begins", playerTurn:"Your turn", attackResult:"Attack result", thinking:"is thinking", finalTurn:"Final turn", won:"You won", lost:"The machine won", draw:"Draw", ready:"Ready", discard:"Discard", clearLastGlyph:"Remove last glyph", clearSelection:"Clear selection", moreOptions:"Show more options", previousPage:"Previous page", myAttacks:"My attacks", machineAttacks:"Machine attacks", perfectOne:"perfect", perfectMany:"perfects", regularOne:"regular", regularMany:"regulars", unlockBotError:"Could not unlock the bot.", networkError:"Connection error. Try again.", closeMatchError:"Could not close the match.", closeMatchNetworkError:"Connection error. The match could not be closed.", startMatchError:"Could not start the match.", attackError:"Could not process the attack.", starting:"Starting...", startGame:"Start match", chooseDifficulty:"Choose", gemOne:"gem", gemMany:"gems", select:"Select", coinHumanStart:"You go first.", coinMachineStart:"The machine goes first.", firstAttackHuman:"You have the first attack.", firstAttackMachine:"The machine has the first attack.", startedByHuman:"you started", startedByMachine:"the machine started", finalDrawDesc:"This is your final turn. If you discover the code, the match is a draw.", chooseAttack:"Choose 4 different glyphs to attack.", attacking:"Attacking...", attack:"Attack", yourAttack:"Your attack", continue:"Continue", botAnalyzing:"The bot is analyzing the attack", chestAlt:"Chest", analyzing:"Analyzing possibilities...", machineAttack:"Machine attack", yourTurn:"Your turn", extraTurnHuman:"You have one more chance.", extraTurnMachine:"The machine has one more chance.", finalReasonHuman:"You discovered the code first. Since you started first, the machine keeps its final turn to try to draw.", finalReasonMachine:"The machine discovered the code first. Since it started first, you keep a final turn to try to draw.", playFinalTurn:"Play my final turn", gameOver:"Match over", opponentCode:"Opponent's code", drawDesc:"Both players discovered the code in their additional turn.", newGame:"New match", home:"Home", coinOne:"coin", coinMany:"coins", balance:"Balance",
} as const;

const spanish = {
  logout:"Cerrar sesión", loggingOut:"Saliendo...", resume:"Reanudar", settings:"Ajustes", general:"General", personalization:"Personalización", nickname:"Nombre de usuario", language:"Idioma",
  glyphSet:"Set de glifos", avatar:"Avatar", theme:"Tema", chest:"Cofre", default:"Predeterminado", numeric:"Numérico",
  dark:"Oscuro", light:"Claro", pink:"Rosa", ocean:"Océano", previous:"Anterior", next:"Siguiente", closeSettings:"Cerrar ajustes",
  saveChanges:"Guardar cambios", saving:"Guardando...", settingsSaved:"Preferencias guardadas.", settingsError:"No se pudieron guardar los ajustes.",
  welcome:"Bienvenido/a", online:"Online", inDevelopment:"En desarrollo", store:"Tienda", ranking:"Ranking", tutorial:"¿Cómo se juega?",
  play:"Jugar", back:"Volver", loading:"Cargando...", retry:"Intentar de nuevo", login:"Iniciar sesión", signup:"Registrate",
  loginTitle:"Iniciar sesión", loginSubtitle:"Entrá para jugar.", email:"Correo", password:"Contraseña", showPassword:"Mostrar contraseña",
  hidePassword:"Ocultar contraseña", loggingIn:"Ingresando...", loginError:"No se pudo iniciar sesión", connectionError:"Error de conexión. Intentá de nuevo.",
  noAccount:"¿No tenés cuenta?", createAccount:"Crear cuenta", signupSubtitle:"Registrate para jugar a Gemlocks.",
  username:"Nombre de usuario", usernameRequired:"El nombre de usuario es obligatorio.", usernameMin:"Debe tener al menos 4 caracteres.",
  usernameMax:"Debe tener como máximo 16 caracteres.", usernameStart:"Debe comenzar con una letra.", usernameChars:"Solo puede contener letras minúsculas y números.",
  passwordRequired:"La contraseña es obligatoria.", passwordMin:"Debe tener al menos 8 caracteres.", passwordMax:"Debe tener como máximo 64 caracteres.",
  passwordSpaces:"No puede contener espacios.", passwordLetter:"Debe contener al menos una letra.", passwordNumber:"Debe contener al menos un número.",
  emailRequired:"El correo es obligatorio.", signupError:"No se pudo crear la cuenta.", creating:"Creando...",
  usernameHint:"4–16 caracteres · empieza con letra · solo letras minúsculas y números",
  passwordHint:"8–64 caracteres · al menos una letra y un número · sin espacios",
  rankPoints:"3 puntos por victoria · 1 por empate", position:"Puesto", player:"Jugador", victories:"Vict.", defeats:"Der.",
  draws:"Emp.", points:"Pts.", noPlayers:"Todavía no hay jugadores.", rankingError:"No se pudo cargar el ranking.",
  backPage:"Atrás", nextPage:"Siguiente", page:"Página",
  purchaseError:"No se pudo completar la compra.", acquired:"Adquirido", confirmChest:"¿Querés adquirir este cofre?", confirmPurchase:"¿Está seguro que desea comprar", purchaseRemaining:"Después de la compra te quedarán", purchasing:"Comprando...", purchase:"Comprar", level:"Nivel", abandon:"Abandonar", toss:"sorteo",
  storeBalance:"Tu saldo", coins:"Monedas", gems:"Gemas", buyCoins:"Adquirir monedas", glyphsCategory:"Glifos", glyphsDescription:"Nuevos símbolos más variados para construir tu código", powerUps:"Power-ups", powerUpsDescription:"Poderes para ganar ventaja en partidas amateur", gemlocksCategory:"Gemlocks", gemlocksDescription:"Adquirí cofres para personalizar tu tesoro", themesCategory:"Temas", themesDescription:"Modificá la estética de todo el juego", avatarsCategory:"Avatares", avatarsDescription:"Un ícono que te represente en tu cuenta", modesCategory:"Modalidades", modesDescription:"Creá partidas online con modos de juego diferentes al básico", bundlesCategory:"Paquetes", bundlesDescription:"Colecciones temáticas con varios artículos", return:"Regresar", specialBundles:"Paquetes especiales", specialBundlesDescription:"Colecciones temáticas que reúnen varios artículos en una sola compra.", coinPacksTitle:"Paquetes de monedas", coinPacksSubtitle:"Elegí el impulso que mejor se adapte a tu partida.", popular:"Popular", smallHelp:"Para una pequeña ayuda", initialBoost:"Un impulso inicial", betterValue:"Más monedas, mejor valor", advanceMore:"Para avanzar mucho más", comingSoon:"Próximamente", futureNote:"Los contenidos son propuestas iniciales; precios y disponibilidad se definirán más adelante.", coinsUnavailable:"Los paquetes de monedas todavía no están disponibles para la compra. Los precios son orientativos y pueden cambiar.", sectionUnavailable:"Esta sección todavía no está disponible.",
  gameMode:"jugador vs máquina", codePrompt:"El adversario intentará descubrir estos 4 glifos.", difficultyPrompt:"Una carrera por descubrir el código secreto del adversario.", whoStarts:"¿Quién empieza?", coinFinished:"sorteo terminado", yourCode:"Tu código:", yourAttacks:"ataques tuyos", history:"Historial", historyEmpty:"Todavía no hay ataques.", discardHint:"Seleccioná qué glifos querés descartar:", startingUnlock:"Desbloqueando...", unlock:"Desbloquear", start:"Comenzar", confirmClose:"¿Está seguro/a de que desea cerrar la partida?", leaveCountsAsLoss:"Esto contaría como derrota.", cancel:"Cancelar", closeMatch:"Cerrar partida",
  tutorialCodeTitle:"Armá un código", tutorialCodeText:"Cada jugador tiene un código secreto de 4 glifos únicos. El objetivo es descubrir el código del adversario antes de que descubra el tuyo.", tutorialDifficultyTitle:"Elegí la dificultad", tutorialDifficultyText:"Antes de empezar elegís uno de los cinco niveles. La dificultad determina cómo piensa y elige sus ataques la máquina.", tutorialCoinTitle:"Se sortea el primer turno", tutorialCoinText:"Una moneda decide quién comienza la partida.", tutorialAttackTitle:"Atacá", tutorialAttackText:"En tu turno armá un código y atacá. Cada ataque se compara con el código secreto del adversario.", tutorialResultsTitle:"Resultados de ataque", tutorialResultsText:"Los perfectos indican glifos correctos en la posición correcta. Los regulares indican glifos correctos en otra posición.", tutorialDiscardTitle:"Usá el descarte", tutorialDiscardText:"Si creés que un glifo no forma parte del código, activá Descartar y bloquealo para tener una ayuda visual durante la partida.", tutorialWinTitle:"Ganá la partida", tutorialWinText:"El primero que descubre el código del adversario gana. Si los cuatro glifos son perfectos, el atacante encontró el código del adversario.", tutorialLabel:"tutorial", tutorialClose:"Cerrar", tutorialBack:"Atrás", tutorialNext:"Siguiente", tutorialSecret:"Secreto", tutorialAttackLabel:"Ataque", tutorialDifficulty:"Dificultad",
  codeTitle:"Elegí tu código", difficultyTitle:"Elegí la dificultad", coinToss:"Tirando la moneda", startMatchTitle:"Comienza la partida", playerTurn:"Tu turno", attackResult:"Resultado del ataque", thinking:"está pensando", finalTurn:"Turno final", won:"Ganaste", lost:"La máquina ganó", draw:"Empate", ready:"Listo", discard:"Descartar", clearLastGlyph:"Borrar último glifo", clearSelection:"Borrar selección", moreOptions:"Mostrar más opciones", previousPage:"Página anterior", myAttacks:"Mis ataques", machineAttacks:"Ataques de la máquina", perfectOne:"perfecto", perfectMany:"perfectos", regularOne:"regular", regularMany:"regulares", unlockBotError:"No se pudo desbloquear el bot.", networkError:"Error de conexión. Intentá de nuevo.", closeMatchError:"No se pudo cerrar la partida.", closeMatchNetworkError:"Error de conexión. La partida no pudo cerrarse.", startMatchError:"No se pudo iniciar la partida", attackError:"No se pudo procesar el ataque", starting:"Iniciando...", startGame:"Comenzar partida", chooseDifficulty:"Elegir", gemOne:"gema", gemMany:"gemas", select:"Seleccionar", coinHumanStart:"Empezás vos.", coinMachineStart:"Empieza la máquina.", firstAttackHuman:"Tenés el primer ataque.", firstAttackMachine:"La máquina tiene el primer ataque.", startedByHuman:"vos empezaste", startedByMachine:"la máquina empezó", finalDrawDesc:"Este es tu turno final. Si descubrís el código, empatás la partida.", chooseAttack:"Elegí 4 glifos distintos para atacar.", attacking:"Atacando...", attack:"Atacar", yourAttack:"Tu ataque", continue:"Continuar", botAnalyzing:"El bot analiza el ataque", chestAlt:"Cofre", analyzing:"Analizando posibilidades...", machineAttack:"Ataque de la máquina", yourTurn:"Tu turno", extraTurnHuman:"Tenés una oportunidad más.", extraTurnMachine:"La máquina tiene una oportunidad más.", finalReasonHuman:"Fuiste el primero en descubrir el código. Como empezaste primero, la máquina conserva su turno final para buscar el empate.", finalReasonMachine:"La máquina fue la primera en descubrir el código. Como empezó primero, conservás un turno final para buscar el empate.", playFinalTurn:"Jugar mi turno final", gameOver:"Partida terminada", opponentCode:"Código del adversario", drawDesc:"Ambos descubrieron el código en su turno adicional.", newGame:"Nueva partida", home:"Inicio", coinOne:"moneda", coinMany:"monedas", balance:"Saldo",
} as const;

export const translations = { en: english, es: spanish, "es-AR": { ...spanish, nickname:"Nick" } };
export type TranslationKey = keyof typeof english;
